<?php
require_once 'flora/utils/BaseDataGenerator.php';

class PollDataGenerator extends BaseDataGenerator {
    protected $table = 'zigu_polls';
    protected $primary_key = 'pollId';
    protected $rows = array (
        array (
            'pollId' => 1, 
            'pollTitle' => 'polltitle1', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        ), 
        array (
            'pollId' => 2, 
            'pollTitle' => 'polltitle2', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        ), 
        array (
            'pollId' => 3, 
            'pollTitle' => 'polltitle3', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        ), 
        array (
            'pollId' => 4, 
            'pollTitle' => 'polltitle4', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        ), 
        array (
            'pollId' => 5, 
            'pollTitle' => 'polltitle5', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        ), 
        array (
            'pollId' => 6, 
            'pollTitle' => 'polltitle6', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        ), 
        array (
            'pollId' => 7, 
            'pollTitle' => 'polltitle7', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        ), 
        array (
            'pollId' => 8, 
            'pollTitle' => 'polltitle8', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        ), 
        array (
            'pollId' => 9, 
            'pollTitle' => 'polltitle9', 
            'limitType' => 1, 
            'pollStatus' => 'online', 
            'resultVisiable' => 1, 
            'freezeTime' => 0, 
            'startTime' => '', 
            'endTime' => '', 
            'resultDisplayorder' => 0, 
            'initCount' => 0, 
            'template' => '', 
            'customTemplate' => '', 
            'templateUrl' => '', 
            'createTime' => '', 
            'createUser' => '', 
            'updateTime' => '', 
            'updateUser' => ''
        )
    );
}